# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f50ede555de15eea781cbd4ed03a09d6288ce607780759e1db21087bf7f1323ecd29682dd46486e89f877fd20922cca153a9524d8047bccf5fbaf303be40d8a7

test:
  secret_key_base: 73aadaa131edc701e5c5f746e07c5d4b12e0b8f6880bcadaab0a6157879c6ff443762a19d7d74452968f962a68887ac54785d387ad18460879a7864a652c6d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
